In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [7]:
pd.__version__

'3.0.5'

In [11]:
len(df)

10000

In [12]:
df['fuel_type'].nunique()

3

In [16]:
x= (df.isnull().sum() > 0).sum()
x

np.int64(2)

In [17]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [24]:
median_before = df['horsepower'].median()
median_before

np.float64(254.0)

In [25]:
most_frequent = df['horsepower'].mode()[0]
most_frequent

np.float64(252.0)

In [26]:
horsepower_filled = df['horsepower'].fillna(most_frequent)
median_after = horsepower_filled.median()
median_after

np.float64(252.0)

In [27]:
import numpy as np

In [31]:
asia = df[df['origin'] == 'Asia']
asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [32]:
X = asia[['vehicle_weight', 'model_year']].iloc[:7].values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [33]:
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [34]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [35]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [36]:
w = XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [37]:
w.sum()

np.float64(0.36919696904925486)